// OCR GCSE Latin Vocabulary (first 50 words from the official list)
const vocabularyData = [
    {latin: "a, ab", english: "from, away from, by", info: "preposition + ablative"},
    {latin: "absum", english: "be absent, be away", info: "abesse, afui - irregular verb"},
    {latin: "ac, atque", english: "and", info: "conjunction"},
    {latin: "accido", english: "happen", info: "accidere, accidi - verb 3"},
    {latin: "accipio", english: "accept, take in, receive", info: "accipere, accepi, acceptus - verb 3"},
    {latin: "ad", english: "to, towards, at", info: "preposition + accusative"},
    {latin: "adeo", english: "so much, so greatly", info: "adverb"},
    {latin: "adsum", english: "be here, be present", info: "adesse, adfui - irregular verb"},
    {latin: "advenio", english: "arrive", info: "advenire, adveni - verb 4"},
    {latin: "aedifico", english: "build", info: "aedificare, aedificavi - verb 1"},
    {latin: "ager", english: "field", info: "agri, m - noun 2"},
    {latin: "ago", english: "do, act, drive", info: "agere, egi, actus - verb 3"},
    {latin: "alius", english: "other, another", info: "alia, aliud - pronoun"},
    {latin: "alter", english: "the other, another", info: "altera, alterum - pronoun"},
    {latin: "altus", english: "high, deep", info: "alta, altum - adjective"},
    {latin: "ambulo", english: "walk", info: "ambulare, ambulavi - verb 1"},
    {latin: "amicus", english: "friend", info: "amici, m - noun 2"},
    {latin: "amo", english: "love, like", info: "amare, amavi, amatus - verb 1"},
    {latin: "amor", english: "love", info: "amoris, m - noun 3"},
    {latin: "ancilla", english: "slave-girl", info: "ancillae, f - noun 1"},
    {latin: "animus", english: "spirit, soul, mind", info: "animi, m - noun 2"},
    {latin: "annus", english: "year", info: "anni, m - noun 2"},
    {latin: "antea", english: "before", info: "adverb"},
    {latin: "aqua", english: "water", info: "aquae, f - noun 1"},
    {latin: "arma", english: "arms, weapons", info: "armorum, n plural - noun 2"},
    {latin: "ars", english: "art, skill", info: "artis, f - noun 3"},
    {latin: "audax", english: "bold, daring", info: "audacis - adjective"},
    {latin: "audeo", english: "dare", info: "audere, ausus sum - verb 2"},
    {latin: "audio", english: "hear, listen to", info: "audire, audivi - verb 4"},
    {latin: "auxilium", english: "help", info: "auxilii, n - noun 2"},
    {latin: "bellum", english: "war", info: "belli, n - noun 2"},
    {latin: "bene", english: "well", info: "adverb"},
    {latin: "bibo", english: "drink", info: "bibere, bibi - verb 3"},
    {latin: "bonus", english: "good", info: "bona, bonum - adjective"},
    {latin: "brevis", english: "short, brief", info: "breve - adjective"},
    {latin: "cado", english: "fall", info: "cadere, cecidi - verb 3"},
    {latin: "caelum", english: "sky, heaven", info: "caeli, n - noun 2"},
    {latin: "capio", english: "take, catch, capture", info: "capere, cepi, captus - verb 3"},
    {latin: "caput", english: "head", info: "capitis, n - noun 3"},
    {latin: "castra", english: "camp", info: "castrorum, n plural - noun 2"},
    {latin: "celer", english: "quick, fast", info: "celeris, celere - adjective"},
    {latin: "cena", english: "dinner, meal", info: "cenae, f - noun 1"},
    {latin: "cibus", english: "food", info: "cibi, m - noun 2"},
    {latin: "civis", english: "citizen", info: "civis, m/f - noun 3"},
    {latin: "clamo", english: "shout", info: "clamare, clamavi - verb 1"},
    {latin: "clarus", english: "famous, clear", info: "clara, clarum - adjective"},
    {latin: "cogito", english: "think, consider", info: "cogitare, cogitavi - verb 1"},
    {latin: "consilium", english: "plan, idea, advice", info: "consilii, n - noun 2"},
    {latin: "contra", english: "against", info: "preposition + accusative"},
    {latin: "cum", english: "with", info: "preposition + ablative"}
];
