// OCR GCSE Latin Vocabulary - Complete list with chapters
const vocabularyData = [
    {latin: "a, ab", english: "from, away from, by", info: "+ ablative (also used as prefix with verbs) - preposition", chapter: 2},
    {latin: "a, ab", english: "away from, by (with passive verb)", info: "+ ablative (also used as prefix with verbs) - preposition", chapter: 7},
    {latin: "absum", english: "be absent, be away, be distant from", info: "abesse, afui - verb irregular", chapter: 6},
    {latin: "ac, atque", english: "and", info: "indeclinable - conjunction", chapter: 9},
    {latin: "accido", english: "happen", info: "accidere, accidi - verb 3", chapter: 9},
    {latin: "accipio", english: "accept, take in, receive", info: "accipere, accepi, acceptus - verb 3", chapter: 6},
    {latin: "ad", english: "to, towards, at", info: "+ accusative (also used as prefix with verbs) - preposition", chapter: 1},
    {latin: "adeo", english: "so much, so greatly, to such an extent", info: "indeclinable - adverb", chapter: 10},
    {latin: "adsum", english: "be here, be present", info: "adesse, adfui - verb irregular", chapter: 6},
    {latin: "advenio", english: "arrive", info: "advenire, adveni - verb 4", chapter: 3},
    {latin: "aedifico", english: "build", info: "aedificare, aedificavi, aedificatus - verb 1", chapter: 3},
    {latin: "ager", english: "field", info: "agri, m - noun 2", chapter: 2},
    {latin: "ago", english: "do, act, drive", info: "agere, egi, actus - verb 3", chapter: 9},
    {latin: "alii … alii", english: "some … others", info: "", chapter: 8},
    {latin: "alius", english: "other, another, else", info: "alia, aliud - pronoun/adjective", chapter: 9},
    {latin: "alter", english: "the other, another, one (of two), the second (of two)", info: "altera, alterum - pronoun/adjective", chapter: 9},
    {latin: "alter…..alter", english: "one…..the other", info: "adjective", chapter: 9},
    {latin: "altus", english: "high, deep", info: "alta, altum - adjective", chapter: 8},
    {latin: "ambulo", english: "walk", info: "ambulare, ambulavi - verb 1", chapter: 1},
    {latin: "amicus", english: "friend", info: "amici, m - noun 2", chapter: 1},
    {latin: "amo", english: "love, like", info: "amare, amavi, amatus - verb 1", chapter: 1},
    {latin: "amor", english: "love", info: "amoris, m - noun 3", chapter: 4},
    {latin: "ancilla", english: "slave-girl, slave-woman", info: "ancillae, f - noun 1", chapter: 1},
    {latin: "animus", english: "spirit, soul, mind", info: "animi, m - noun 2", chapter: 7},
    {latin: "annus", english: "year", info: "anni, m - noun 2", chapter: 2},
    {latin: "antea", english: "before", info: "indeclinable - adverb", chapter: 9},
    {latin: "appropinquo", english: "approach, come near to", info: "appropinquare, appropinquavi + dative - verb 1", chapter: 6},
    {latin: "aqua", english: "water", info: "aquae, f - noun 1", chapter: 2},
    {latin: "arma", english: "arms, weapons", info: "armorum, n plural - noun 2 plural", chapter: 2},
    {latin: "ars", english: "art, skill", info: "artis, f - noun 3", chapter: 8},
    {latin: "ascendo", english: "climb", info: "ascendere, ascendi, ascensus - verb 3", chapter: 5},
    {latin: "audax", english: "bold, daring", info: "audacis - adjective", chapter: 7},
    {latin: "audeo", english: "dare", info: "audere, ausus sum - verb 2", chapter: 9},
    {latin: "audio", english: "hear, listen to", info: "audire, audivi, auditus - verb 4", chapter: 2},
    {latin: "aufero", english: "take away, carry off, steal", info: "auferre, abstuli, ablatus - verb irregular", chapter: 8},
    {latin: "auxilium", english: "help", info: "auxilii, n - noun 2", chapter: 2},
    {latin: "bellum", english: "war", info: "belli, n - noun 2", chapter: 2},
    {latin: "bene", english: "well", info: "indeclinable - adverb", chapter: 5},
    {latin: "bibo", english: "drink", info: "bibere, bibi - verb 3", chapter: 2},
    {latin: "bonus", english: "good", info: "bona, bonum - adjective", chapter: 3},
    {latin: "brevis", english: "short, brief", info: "breve - adjective", chapter: 10},
    {latin: "cado", english: "fall", info: "cadere, cecidi, casus - verb 3", chapter: 3},
    {latin: "caelum", english: "sky, heaven", info: "caeli, n - noun 2", chapter: 4},
    {latin: "capio", english: "take, catch, capture, make (a plan)", info: "capere, cepi, captus - verb 3", chapter: 4},
    {latin: "captivus", english: "captive, prisoner", info: "captivi, m - noun 2", chapter: 7},
    {latin: "caput", english: "head", info: "capitis, n - noun 3", chapter: 4},
    {latin: "castra", english: "camp", info: "castrorum, n plural - noun 2", chapter: 7},
    {latin: "celer", english: "quick, fast", info: "celeris, celere - adjective", chapter: 5},
    {latin: "celo", english: "hide", info: "celare, celavi, celatus - verb 1", chapter: 7},
    {latin: "cena", english: "dinner, meal", info: "cenae, f - noun 1", chapter: 3},
    {latin: "ceteri", english: "the rest, the others", info: "ceterae, cetera - adjective", chapter: 8},
    {latin: "cibus", english: "food", info: "cibi, m - noun 2", chapter: 1},
    {latin: "circum", english: "around", info: "+ accusative - preposition", chapter: 1},
    {latin: "civis", english: "citizen", info: "civis, m and f - noun 3", chapter: 5},
    {latin: "clamo", english: "shout", info: "clamare, clamavi, clamatus - verb 1", chapter: 1},
    {latin: "clamor", english: "shout, shouting, noise", info: "clamoris, m - noun 3", chapter: 4},
    {latin: "clarus", english: "famous, clear", info: "clara, clarum - adjective", chapter: 7},
    {latin: "coepi", english: "began", info: "coepisse - verb irregular", chapter: 8},
    {latin: "cogito", english: "think, consider", info: "cogitare, cogitavi, cogitatus - verb 1", chapter: 10},
    {latin: "cognosco", english: "get to know, find out", info: "cognoscere, cognovi, cognitus - verb 3", chapter: 9},
    {latin: "cogo", english: "force, compel", info: "cogere, coegi, coactus - verb 3", chapter: 8},
    {latin: "comes", english: "comrade, companion", info: "comitis, m and f - noun 3", chapter: 7},
    {latin: "conficio", english: "finish, wear out", info: "conficere, confeci, confectus - verb 3", chapter: 8},
    {latin: "conor", english: "try", info: "conari, conatus sum - verb 1 deponent", chapter: 9},
    {latin: "consilium", english: "plan, idea, advice", info: "consilii, n - noun 2", chapter: 3},
    {latin: "conspicio", english: "catch sight of, notice", info: "conspicere, conspexi, conspectus - verb 3", chapter: 6},
    {latin: "constituo", english: "decide", info: "constituere, constitui, constitutus - verb 3", chapter: 6},
    {latin: "consul", english: "consul", info: "consulis, m - noun 3", chapter: 7},
    {latin: "consumo", english: "eat", info: "consumere, consumpsi, consumptus - verb 3", chapter: 3},
    {latin: "contra", english: "against", info: "+ accusative - preposition", chapter: 1},
    {latin: "convenio", english: "come together, gather, meet", info: "convenire, conveni - verb 4", chapter: 6},
    {latin: "copiae", english: "forces, troops", info: "copiarum, f plural - noun 1 plural", chapter: 9},
    {latin: "corpus", english: "body", info: "corporis, n - noun 3", chapter: 7},
    {latin: "cras", english: "tomorrow", info: "indeclinable - adverb", chapter: 5},
    {latin: "credo", english: "believe, trust", info: "credere, credidi, creditus + dative - verb 3", chapter: 5},
    {latin: "crudelis", english: "cruel", info: "crudele - adjective", chapter: 7},
    {latin: "cum", english: "with", info: "+ ablative - preposition", chapter: 2},
    {latin: "cum", english: "when, since", info: "indeclinable - conjunction", chapter: 10},
    {latin: "cupio", english: "want, desire", info: "cupere, cupivi, cupitus - verb 3", chapter: 6},
    {latin: "cur?", english: "why?", info: "indeclinable - adverb", chapter: 4},
    {latin: "cura", english: "care, worry", info: "curae, f - noun 1", chapter: 10},
    {latin: "curro", english: "run", info: "currere, cucurri, cursus - verb 3", chapter: 3},
    {latin: "custodio", english: "guard", info: "custodire, custodivi, custoditus - verb 4", chapter: 2},
    {latin: "custos", english: "guard", info: "custodis, m and f - noun 3", chapter: 7},
    {latin: "de", english: "from, down from, about", info: "+ ablative - preposition", chapter: 2},
    {latin: "dea", english: "goddess", info: "deae, f - noun 1", chapter: 1},
    {latin: "debeo", english: "owe, ought, should, must", info: "debere, debui, debitus - verb 2", chapter: 3},
    {latin: "decem", english: "ten", info: "indeclinable - numeral", chapter: 2},
    {latin: "defendo", english: "defend", info: "defendere, defendi, defensus - verb 3", chapter: 5},
    {latin: "deinde", english: "then", info: "indeclinable - adverb", chapter: 3},
    {latin: "deleo", english: "destroy", info: "delere, delevi, deletus - verb 2", chapter: 3},
    {latin: "descendo", english: "go down, come down", info: "descendere, descendi, descensus - verb 3", chapter: 6},
    {latin: "deus", english: "god", info: "dei, m - noun 2", chapter: 1},
    {latin: "dico", english: "say, speak, tell", info: "dicere, dixi, dictus - verb 3", chapter: 6},
    {latin: "dies", english: "day", info: "diei, m - noun 5", chapter: 10},
    {latin: "difficilis", english: "difficult", info: "difficile - adjective", chapter: 5},
    {latin: "diligens", english: "careful", info: "diligentis - adjective", chapter: 10},
    {latin: "dirus", english: "dreadful", info: "dira, dirum - adjective", chapter: 10},
    {latin: "discedo", english: "depart, leave", info: "discedere, discessi - verb 3", chapter: 3},
    {latin: "diu", english: "for a long time", info: "indeclinable - adverb", chapter: 3},
    {latin: "do", english: "give", info: "dare, dedi, datus - verb 1", chapter: 2},
    {latin: "doceo", english: "teach", info: "docere, docui, doctus - verb 2", chapter: 8},
    {latin: "domina", english: "mistress", info: "dominae, f - noun 1", chapter: 3},
    {latin: "dominus", english: "master", info: "domini, m - noun 2", chapter: 1},
    {latin: "domus", english: "home", info: "domus, f (domi = at home) - noun 4", chapter: 10},
    {latin: "donum", english: "gift, present", info: "doni, n - noun 2", chapter: 2},
    {latin: "dormio", english: "sleep", info: "dormire, dormivi - verb 4", chapter: 2},
    {latin: "duco", english: "lead, take", info: "ducere, duxi, ductus - verb 3", chapter: 2},
    {latin: "dum", english: "while, until", info: "indeclinable - conjunction", chapter: 10},
    {latin: "dux", english: "leader", info: "ducis, m - noun 3", chapter: 4},
    {latin: "e, ex", english: "from, out of, out", info: "+ ablative (also used as prefix with verbs) - preposition", chapter: 2},
    {latin: "ecce!", english: "look!", info: "indeclinable - adverb", chapter: 5},
    {latin: "effugio", english: "escape", info: "effugere, effugi - verb 3", chapter: 6},
    {latin: "ego", english: "I, me", info: "mei - pronoun", chapter: 4},
    {latin: "egredior", english: "go out", info: "egredi, egressus sum - verb 3 deponent", chapter: 9},
    {latin: "emo", english: "buy", info: "emere, emi, emptus - verb 3", chapter: 6},
    {latin: "enim", english: "for", info: "indeclinable - conjunction", chapter: 5},
    {latin: "eo", english: "go", info: "ire, i(v)i - verb irregular", chapter: 6},
    {latin: "epistula", english: "letter", info: "epistulae, f - noun 1", chapter: 1},
    {latin: "equus", english: "horse", info: "equi, m - noun 2", chapter: 1},
    {latin: "et", english: "and, even", info: "indeclinable - conjunction", chapter: 1},
    {latin: "et ... et", english: "both ... and", info: "indeclinable", chapter: 7},
    {latin: "etiam", english: "also, even", info: "indeclinable - adverb", chapter: 9},
    {latin: "exercitus", english: "army", info: "exercitus, m - noun 4", chapter: 10},
    {latin: "exspecto", english: "wait for, expect", info: "exspectare, exspectavi, exspectatus - verb 1", chapter: 6},
    {latin: "facilis", english: "easy", info: "facile - adjective", chapter: 5},
    {latin: "facio", english: "make, do", info: "facere, feci, factus - verb 3", chapter: 4},
    {latin: "faveo", english: "favour, support", info: "favere, favi, fautus + dative - verb 2", chapter: 10},
    {latin: "felix", english: "fortunate, happy", info: "felicis - adjective", chapter: 10},
    {latin: "femina", english: "woman", info: "feminae, f - noun 1", chapter: 1},
    {latin: "fero", english: "bring, carry, bear", info: "ferre, tuli, latus - verb irregular", chapter: 8},
    {latin: "ferox", english: "fierce, ferocious", info: "ferocis - adjective", chapter: 5},
    {latin: "festino", english: "hurry", info: "festinare, festinavi - verb 1", chapter: 3},
    {latin: "fidelis", english: "faithful, loyal", info: "fidele - adjective", chapter: 9},
    {latin: "filia", english: "daughter", info: "filiae, f - noun 1", chapter: 5},
    {latin: "filius", english: "son", info: "filii, m - noun 2", chapter: 5},
    {latin: "flumen", english: "river", info: "fluminis, n - noun 3", chapter: 7},
    {latin: "forte", english: "by chance", info: "indeclinable - adverb", chapter: 5},
    {latin: "fortis", english: "brave", info: "forte - adjective", chapter: 5},
    {latin: "forum", english: "forum, market place", info: "fori, n - noun 2", chapter: 3},
    {latin: "frater", english: "brother", info: "fratris, m - noun 3", chapter: 4},
    {latin: "frustra", english: "in vain", info: "indeclinable - adverb", chapter: 8},
    {latin: "fugio", english: "run away, flee", info: "fugere, fugi - verb 3", chapter: 4},
    {latin: "gaudeo", english: "be pleased, rejoice", info: "gaudere, gavisus sum - verb 2", chapter: 9},
    {latin: "gaudium", english: "joy, pleasure", info: "gaudii, n - noun 2", chapter: 10},
    {latin: "gens", english: "family, tribe, race, people", info: "gentis, f - noun 3", chapter: 9},
    {latin: "gero", english: "wear (clothes), wage (war)", info: "gerere, gessi, gestus - verb 3", chapter: 7},
    {latin: "gladius", english: "sword", info: "gladii, m - noun 2", chapter: 1},
    {latin: "gravis", english: "heavy, serious", info: "grave - adjective", chapter: 5},
    {latin: "habeo", english: "have, hold", info: "habere, habui, habitus - verb 2", chapter: 2},
    {latin: "habito", english: "live", info: "habitare, habitavi, habitatus - verb 1", chapter: 3},
    {latin: "heri", english: "yesterday", info: "indeclinable - adverb", chapter: 5},
    {latin: "hic", english: "this, he, she, it", info: "haec, hoc - pronoun", chapter: 7},
    {latin: "hodie", english: "today", info: "indeclinable - adverb", chapter: 5},
    {latin: "homo", english: "man, human being", info: "hominis, m - noun 3", chapter: 8},
    {latin: "hora", english: "hour", info: "horae, f - noun 1", chapter: 2},
    {latin: "hortor", english: "encourage, urge", info: "hortari, hortatus sum - verb 1 deponent", chapter: 9},
    {latin: "hortus", english: "garden", info: "horti, m - noun 2", chapter: 1},
    {latin: "hostis", english: "enemy", info: "hostis, m - noun 3", chapter: 6},
    {latin: "iaceo", english: "lie", info: "iacere, iacui - verb 2", chapter: 10},
    {latin: "iacio", english: "throw", info: "iacere, ieci, iactus (in compounds -icio) - verb 3", chapter: 6},
    {latin: "iam", english: "now, already", info: "indeclinable - adverb", chapter: 7},
    {latin: "ianua", english: "door", info: "ianuae, f - noun 1", chapter: 10},
    {latin: "ibi", english: "there", info: "indeclinable - adverb", chapter: 7},
    {latin: "idem", english: "the same", info: "eadem, idem - pronoun", chapter: 8},
    {latin: "igitur", english: "therefore, and so", info: "indeclinable - adverb", chapter: 5},
    {latin: "ille", english: "that, he, she, it", info: "illa, illud - pronoun", chapter: 7},
    {latin: "imperator", english: "emperor, general, leader", info: "imperatoris, m - noun 3", chapter: 7},
    {latin: "imperium", english: "empire, power, command", info: "imperii, n - noun 2", chapter: 8},
    {latin: "impero", english: "order, command", info: "imperare, imperavi, imperatus + dative - verb 1", chapter: 10},
    {latin: "in", english: "in, on", info: "+ ablative (also used as prefix with verbs) - preposition", chapter: 2},
    {latin: "in", english: "into, onto", info: "+ accusative (also used as prefix with verbs) - preposition", chapter: 1},
    {latin: "incendo", english: "burn, set on fire", info: "incendere, incendi, incensus - verb 3", chapter: 7},
    {latin: "infelix", english: "unlucky, unhappy", info: "infelicis - adjective", chapter: 10},
    {latin: "ingens", english: "huge", info: "ingentis - adjective", chapter: 5},
    {latin: "ingredior", english: "enter", info: "ingredi, ingressus sum - verb 3 deponent", chapter: 9},
    {latin: "inimicus", english: "enemy", info: "inimici, m - noun 2", chapter: 8},
    {latin: "inquit", english: "he/she says, he/she said", info: "verb irregular", chapter: 2},
    {latin: "insula", english: "island, block of flats", info: "insulae, f - noun 1", chapter: 1},
    {latin: "intellego", english: "understand, realise", info: "intellegere, intellexi, intellectus - verb 3", chapter: 6},
    {latin: "inter", english: "among, between", info: "+ accusative - preposition", chapter: 3},
    {latin: "interea", english: "meanwhile", info: "indeclinable - adverb", chapter: 9},
    {latin: "interficio", english: "kill", info: "interficere, interfeci, interfectus - verb 3", chapter: 6},
    {latin: "intro", english: "enter", info: "intrare, intravi, intratus - verb 1", chapter: 6},
    {latin: "invenio", english: "find", info: "invenire, inveni, inventus - verb 4", chapter: 2},
    {latin: "invito", english: "invite", info: "invitare, invitavi, invitatus - verb 1", chapter: 3},
    {latin: "ipse", english: "himself, herself, itself, themselves", info: "ipsa, ipsum - pronoun", chapter: 8},
    {latin: "ira", english: "anger", info: "irae, f - noun 1", chapter: 6},
    {latin: "iratus", english: "angry", info: "irata, iratum - adjective", chapter: 3},
    {latin: "is", english: "this, that, he, she, it, them", info: "ea, id - pronoun", chapter: 5},
    {latin: "ita", english: "in this way, to such an extent, so", info: "indeclinable - adverb", chapter: 10},
    {latin: "itaque", english: "and so, therefore", info: "indeclinable - adverb", chapter: 10},
    {latin: "iter", english: "journey", info: "itineris, n - noun 3", chapter: 4},
    {latin: "iterum", english: "again", info: "indeclinable - adverb", chapter: 9},
    {latin: "iubeo", english: "order", info: "iubere, iussi, iussus - verb 2", chapter: 2},
    {latin: "iuvenis", english: "young man", info: "iuvenis, m - noun 3", chapter: 4},
    {latin: "labor", english: "work, toil", info: "laboris, m - noun 3", chapter: 8},
    {latin: "laboro", english: "work, toil", info: "laborare, laboravi - verb 1", chapter: 1},
    {latin: "lacrimo", english: "weep, cry", info: "lacrimare, lacrimavi - verb 1", chapter: 3},
    {latin: "laetus", english: "happy", info: "laeta, laetum - adjective", chapter: 3},
    {latin: "laudo", english: "praise", info: "laudare, laudavi, laudatus - verb 1", chapter: 7},
    {latin: "legio", english: "legion", info: "legionis, f - noun 3", chapter: 10},
    {latin: "lego", english: "read, choose", info: "legere, legi, lectus - verb 3", chapter: 2},
    {latin: "lentus", english: "slow", info: "lenta, lentum - adjective", chapter: 9},
    {latin: "libenter", english: "willingly, gladly", info: "indeclinable - adverb", chapter: 9},
    {latin: "liber", english: "book", info: "libri, m - noun 2", chapter: 2},
    {latin: "liberi", english: "children", info: "liberorum, m plural - noun 2", chapter: 9},
    {latin: "libero", english: "set free", info: "liberare, liberavi, liberatus - verb 1", chapter: 6},
    {latin: "libertus", english: "freedman, ex-slave", info: "liberti, m - noun 2", chapter: 3},
    {latin: "locus", english: "place", info: "loci, m - noun 2", chapter: 5},
    {latin: "longus", english: "long", info: "longa, longum - adjective", chapter: 4},
    {latin: "loquor", english: "speak, talk", info: "loqui, locutus sum - verb 3 deponent", chapter: 9},
    {latin: "lux", english: "light, daylight", info: "lucis, f - noun 3", chapter: 10},
    {latin: "maior", english: "bigger, greater", info: "gen. maioris, (neuter maius) - adj 3", chapter: 7},
    {latin: "magnus", english: "big, large, great", info: "magna, magnum - adjective 3 comp", chapter: 3},
    {latin: "malo", english: "prefer", info: "malle, malui - verb irregular", chapter: 8},
    {latin: "malus", english: "evil, bad", info: "mala, malum - adjective", chapter: 3},
    {latin: "maneo", english: "remain, stay", info: "manere, mansi - verb 2", chapter: 3},
    {latin: "manus", english: "hand, group of people", info: "manus, f - noun 4", chapter: 10},
    {latin: "mare", english: "sea", info: "maris, n - noun 3", chapter: 4},
    {latin: "maritus", english: "husband", info: "mariti, m - noun 2", chapter: 4},
    {latin: "mater", english: "mother", info: "matris, f - noun 3", chapter: 4},
    {latin: "maxime", english: "very greatly", info: "indeclinable - adverb", chapter: 7},
    {latin: "maximus", english: "very big, greatest, biggest", info: "maxima maximum - adjective superl", chapter: 7},
    {latin: "medius", english: "middle", info: "media, medium - adjective", chapter: 4},
    {latin: "melior", english: "better", info: "gen. melioris; neut melius - adjective 3 comp", chapter: 7},
    {latin: "meus", english: "my", info: "mea, meum - pronoun", chapter: 4},
    {latin: "miles", english: "soldier", info: "militis, m - noun 3", chapter: 4},
    {latin: "minime", english: "very little, least, no!", info: "indeclinable - adverb", chapter: 7},
    {latin: "minimus", english: "very little, smallest", info: "minima minimum - adjective superl", chapter: 7},
    {latin: "minor", english: "smaller, less", info: "gen. minoris; neut. minus - adjective 3 comp", chapter: 7},
    {latin: "miror", english: "wonder at, admire", info: "mirari, miratus sum - verb 1 deponent", chapter: 9},
    {latin: "miser", english: "miserable, wretched, sad", info: "misera, miserum - adjective", chapter: 3},
    {latin: "mitto", english: "send", info: "mittere, misi, missus - verb 3", chapter: 2},
    {latin: "modus", english: "manner, way, kind", info: "modi, m - noun 2", chapter: 7},
    {latin: "moneo", english: "warn, advise", info: "monere, monui, monitus - verb 2", chapter: 2},
    {latin: "mons", english: "mountain", info: "montis, m - noun 3", chapter: 5},
    {latin: "morior", english: "die", info: "mori, mortuus sum - verb 3 deponent", chapter: 9},
    {latin: "mors", english: "death", info: "mortis, f - noun 3", chapter: 5},
    {latin: "moveo", english: "move", info: "movere, movi, motus - verb 2", chapter: 7},
    {latin: "mox", english: "soon", info: "indeclinable - adverb", chapter: 5},
    {latin: "multo", english: "much", info: "indeclinable - adverb", chapter: 7},
    {latin: "multus", english: "much, many", info: "multa, multum - adjective", chapter: 3},
    {latin: "murus", english: "wall", info: "muri, m - noun 2", chapter: 2},
    {latin: "nam", english: "for", info: "indeclinable - conjunction", chapter: 8},
    {latin: "narro", english: "tell, relate", info: "narrare, narravi, narratus - verb 1", chapter: 7},
    {latin: "nauta", english: "sailor", info: "nautae, m - noun 1", chapter: 3},
    {latin: "navigo", english: "sail", info: "navigare, navigavi - verb 1", chapter: 1},
    {latin: "navis", english: "ship", info: "navis, f - noun 3", chapter: 4},
    {latin: "-ne", english: "(introduces question)", info: "indeclinable - particle", chapter: 4},
    {latin: "ne", english: "that ... not, so that ... not, that, lest", info: "indeclinable + subjunctive - conjunction", chapter: 0},
    {latin: "nec, neque", english: "and not, nor, neither", info: "indeclinable - conjunction", chapter: 8},
    {latin: "nec/neque..nec/neque", english: "neither…..nor", info: "indeclinable - conjunction", chapter: 8},
    {latin: "neco", english: "kill", info: "necare, necavi, necatus - verb 1", chapter: 1},
    {latin: "nemo", english: "no one, nobody", info: "nullius - noun irregular", chapter: 9},
    {latin: "nescio", english: "not know", info: "nescire, nescivi - verb 4", chapter: 10},
    {latin: "nihil", english: "nothing", info: "indeclinable - noun irregular", chapter: 7},
    {latin: "nisi", english: "unless, except", info: "indeclinable - conjunction", chapter: 8},
    {latin: "nolo", english: "not want, refuse", info: "nolle, nolui - verb irregular", chapter: 8},
    {latin: "nomen", english: "name", info: "nominis, n - noun 3", chapter: 4},
    {latin: "non", english: "not", info: "indeclinable - adverb", chapter: 1},
    {latin: "nonne …?", english: "surely ... ?", info: "indeclinable - adverb", chapter: 4},
    {latin: "nonnulli", english: "some, several", info: "nonnullae, nonnulla - adjective", chapter: 9},
    {latin: "nos", english: "we, us", info: "nostrum - pronoun", chapter: 5},
    {latin: "noster", english: "our", info: "nostra, nostrum - pronoun", chapter: 5},
    {latin: "novus", english: "new", info: "nova, novum - adjective", chapter: 3},
    {latin: "nox", english: "night", info: "noctis, f - noun 3", chapter: 4},
    {latin: "nullus", english: "not any, no", info: "nulla, nullum - adjective", chapter: 8},
    {latin: "num", english: "whether", info: "indeclinable - particle", chapter: 10},
    {latin: "num ... ?", english: "surely … not?", info: "indeclinable - particle", chapter: 4},
    {latin: "numquam", english: "never", info: "indeclinable - adverb", chapter: 5},
    {latin: "nunc", english: "now", info: "indeclinable - adverb", chapter: 1},
    {latin: "nuntio", english: "announce, report", info: "nuntiare, nuntiavi, nuntiatus - verb 1", chapter: 6},
    {latin: "nuntius", english: "messenger, message, news", info: "nuntii, m - noun 2", chapter: 1},
    {latin: "occido", english: "kill", info: "occidere, occidi, occisus - verb 3", chapter: 10},
    {latin: "offero", english: "offer", info: "offerre, obtuli, oblatus - verb irregular", chapter: 8},
    {latin: "olim", english: "once, some time ago", info: "indeclinable - adverb", chapter: 5},
    {latin: "omnis", english: "all, every", info: "omne - adjective", chapter: 5},
    {latin: "opprimo", english: "crush, overwhelm", info: "opprimere, oppressi, oppressus - verb 3", chapter: 9},
    {latin: "oppugno", english: "attack", info: "oppugnare, oppugnavi, oppugnatus - verb 1", chapter: 3},
    {latin: "optimus", english: "best, excellent, very good", info: "optima, optimum - adjective 3 superl", chapter: 7},
    {latin: "oro", english: "beg", info: "orare, oravi, oratus - verb 1", chapter: 10},
    {latin: "ostendo", english: "show", info: "ostendere, ostendi, ostentus - verb 3", chapter: 8},
    {latin: "paene", english: "almost, nearly", info: "indeclinable - adverb", chapter: 10},
    {latin: "paro", english: "prepare, provide", info: "parare, paravi, paratus - verb 1", chapter: 1},
    {latin: "pars", english: "part", info: "partis, f - noun 3", chapter: 7},
    {latin: "parvus", english: "small", info: "parva, parvum - adjective", chapter: 3},
    {latin: "pater", english: "father", info: "patris, m - noun 3", chapter: 4},
    {latin: "patior", english: "suffer, endure", info: "pati, passus sum - verb 3 deponent", chapter: 9},
    {latin: "patria", english: "country, homeland", info: "patriae, f - noun 1", chapter: 3},
    {latin: "pauci", english: "few, a few", info: "paucae, pauca - adjective plural", chapter: 7},
    {latin: "pax", english: "peace", info: "pacis, f - noun 3", chapter: 5},
    {latin: "pecunia", english: "money", info: "pecuniae, f - noun 1", chapter: 1},
    {latin: "peior", english: "worse", info: "gen. peioris; neut. peius - adjective 3 comp", chapter: 7},
    {latin: "pello", english: "drive", info: "pellere, pepuli, pulsus - verb 3", chapter: 10},
    {latin: "per", english: "through, along", info: "+ accusative - preposition", chapter: 1},
    {latin: "pereo", english: "die, perish", info: "perire, perii - verb irregular", chapter: 6},
    {latin: "periculum", english: "danger", info: "periculi, n - noun 2", chapter: 2},
    {latin: "persuadeo", english: "persuade", info: "persuadere, persuasi + dative - verb 2", chapter: 6},
    {latin: "perterritus", english: "terrified", info: "perterrita, perterritum - adjective", chapter: 6},
    {latin: "pes", english: "foot", info: "pedis, m - noun 3", chapter: 10},
    {latin: "pessimus", english: "worst, very bad", info: "pessima pessimum - adjective superl", chapter: 7},
    {latin: "peto", english: "make for, seek, beg/ask for", info: "petere, petivi, petitus - verb 3", chapter: 4},
    {latin: "plurimus", english: "very much; pl very many, most", info: "plurima, plurimum - adjective superl", chapter: 7},
    {latin: "plus", english: "more of (+gen); pl more", info: "gen. pluris - adjective 3 comp", chapter: 7},
    {latin: "poena", english: "punishment", info: "poenae, f - noun 1", chapter: 10},
    {latin: "poenas do", english: "pay the penalty, be punished", info: "", chapter: 10},
    {latin: "pono", english: "put, place, set up", info: "ponere, posui, positus - verb 3", chapter: 5},
    {latin: "porta", english: "gate", info: "portae, f - noun 1", chapter: 3},
    {latin: "porto", english: "carry, bear, take", info: "portare, portavi, portatus - verb 1", chapter: 1},
    {latin: "possum", english: "can, be able", info: "posse, potui - verb irregular", chapter: 3},
    {latin: "post", english: "after, behind", info: "+ accusative - preposition", chapter: 4},
    {latin: "postea", english: "afterwards", info: "indeclinable - adverb", chapter: 8},
    {latin: "postquam", english: "after, when", info: "indeclinable - conjunction", chapter: 6},
    {latin: "postridie", english: "on the next day", info: "indeclinable - adverb", chapter: 10},
    {latin: "praemium", english: "prize, reward, profit", info: "praemii, n - noun 2", chapter: 8},
    {latin: "primo", english: "at first", info: "indeclinable - adverb", chapter: 7},
    {latin: "primus", english: "first", info: "prima, primum - adjective", chapter: 4},
    {latin: "princeps", english: "chief, emperor", info: "principis, m - noun 3", chapter: 10},
    {latin: "pro", english: "in front of, for, in return for", info: "+ ablative - preposition", chapter: 9},
    {latin: "procedo", english: "advance, proceed", info: "procedere, processi - verb 3", chapter: 10},
    {latin: "proelium", english: "battle", info: "proelii, n - noun 2", chapter: 8},
    {latin: "proficiscor", english: "set out", info: "proficisci, profectus sum - verb 3 deponent", chapter: 9},
    {latin: "progredior", english: "advance", info: "progredi, progressus sum - verb 3 deponent", chapter: 9},
    {latin: "promitto", english: "promise", info: "promittere, promisi, promissus - verb 3", chapter: 8},
    {latin: "prope", english: "near", info: "+ accusative - preposition", chapter: 6},
    {latin: "propter", english: "on account of, because of", info: "+ accusative - preposition", chapter: 9},
    {latin: "proximus", english: "nearest, next to", info: "proxima, proximum - adjective", chapter: 9},
    {latin: "puella", english: "girl", info: "puellae, f - noun 1", chapter: 1},
    {latin: "puer", english: "boy", info: "pueri, m - noun 2", chapter: 2},
    {latin: "pugno", english: "fight", info: "pugnare, pugnavi - verb 1", chapter: 1},
    {latin: "pulcher", english: "beautiful, handsome", info: "pulchra, pulchrum - adjective", chapter: 3},
    {latin: "punio", english: "punish", info: "punire, punivi, punitus - verb 4", chapter: 2},
    {latin: "puto", english: "think", info: "putare, putavi, putatus - verb 1", chapter: 9},
    {latin: "quaero", english: "search for, look for, ask", info: "quaerere, quaesivi, quaesitus - verb 3", chapter: 3},
    {latin: "qualis?", english: "what sort of?", info: "quale - adjective", chapter: 8},
    {latin: "quam", english: "as … as possible", info: "+ superlative adverb", chapter: 7},
    {latin: "quam", english: "than, how … ? how … !", info: "indeclinable - adverb", chapter: 7},
    {latin: "quamquam", english: "although", info: "indeclinable - conjunction", chapter: 6},
    {latin: "quando?", english: "when?", info: "indeclinable - adverb", chapter: 4},
    {latin: "quantus?", english: "how big? how much?", info: "quanta? quantum? - adjective", chapter: 8},
    {latin: "-que", english: "and", info: "indeclinable - conjunction", chapter: 3},
    {latin: "qui", english: "who, which", info: "quae, quod - pronoun", chapter: 6},
    {latin: "quidam", english: "one, a certain, some", info: "quaedam, quoddam - pronoun", chapter: 9},
    {latin: "quinque", english: "five", info: "indeclinable - numeral", chapter: 2},
    {latin: "quis?", english: "who? what?", info: "quid? - pronoun", chapter: 6},
    {latin: "quo?", english: "to where?", info: "indeclinable - adverb", chapter: 4},
    {latin: "quod", english: "because", info: "indeclinable - conjunction", chapter: 6},
    {latin: "quomodo?", english: "how?", info: "indeclinable - adverb", chapter: 8},
    {latin: "quoque", english: "also, too", info: "indeclinable - conjunction", chapter: 8},
    {latin: "quot?", english: "how many?", info: "indeclinable - adjective", chapter: 8},
    {latin: "rapio", english: "seize, grab", info: "rapere, rapui, raptus - verb 3", chapter: 8},
    {latin: "re-", english: "- back", info: "(prefix used with verbs) - prefix", chapter: 6},
    {latin: "reddo", english: "give back, restore", info: "reddere, reddidi, redditus - verb 3", chapter: 9},
    {latin: "redeo", english: "go back, come back, return", info: "redire, redii - verb irregular", chapter: 6},
    {latin: "refero", english: "bring/carry back, report, tell", info: "referre, rettuli, relatus - verb irregular", chapter: 8},
    {latin: "regina", english: "queen", info: "reginae, f - noun 1", chapter: 4},
    {latin: "regnum", english: "kingdom", info: "regni, n - noun 2", chapter: 4},
    {latin: "rego", english: "rule", info: "regere, rexi, rectus - verb 3", chapter: 5},
    {latin: "regredior", english: "go back, return", info: "regredi, regressus sum - verb 3 deponent", chapter: 9},
    {latin: "relinquo", english: "leave, leave behind", info: "relinquere, reliqui, relictus - verb 3", chapter: 4},
    {latin: "res", english: "thing, matter, event", info: "rei, f - noun 5", chapter: 10},
    {latin: "resisto", english: "resist", info: "resistere, restiti + dative - verb 3", chapter: 7},
    {latin: "respondeo", english: "reply", info: "respondere, respondi, responsus - verb 2", chapter: 6},
    {latin: "rex", english: "king", info: "regis, m - noun 3", chapter: 4},
    {latin: "rideo", english: "laugh, smile", info: "ridere, risi - verb 2", chapter: 4},
    {latin: "rogo", english: "ask, ask for", info: "rogare, rogavi, rogatus - verb 1", chapter: 5},
    {latin: "Roma", english: "Rome", info: "Romae, f (Romae: at/in Rome) - noun 1", chapter: 1},
    {latin: "Romanus", english: "Roman", info: "Romana, Romanum - adjective", chapter: 3},
    {latin: "sacer", english: "sacred", info: "sacra, sacrum - adjective", chapter: 8},
    {latin: "saepe", english: "often", info: "indeclinable - adverb", chapter: 5},
    {latin: "saevus", english: "savage, cruel", info: "saeva, saevum - adjective", chapter: 5},
    {latin: "saluto", english: "greet", info: "salutare, salutavi, salutatus - verb 1", chapter: 1},
    {latin: "sanguis", english: "blood", info: "sanguinis, m - noun 3", chapter: 7},
    {latin: "scelestus", english: "wicked", info: "scelesta, scelestum - adjective", chapter: 8},
    {latin: "scelus", english: "crime", info: "sceleris, n - noun 3", chapter: 8},
    {latin: "scio", english: "know", info: "scire, scivi, scitus - verb 4", chapter: 9},
    {latin: "scribo", english: "write", info: "scribere, scripsi, scriptus - verb 3", chapter: 2},
    {latin: "se", english: "himself, herself, itself, themselves", info: "sui - pronoun", chapter: 5},
    {latin: "sed", english: "but", info: "indeclinable - conjunction", chapter: 1},
    {latin: "sedeo", english: "sit", info: "sedere, sedi - verb 2", chapter: 2},
    {latin: "semper", english: "always", info: "indeclinable - adverb", chapter: 1},
    {latin: "senator", english: "senator", info: "senatoris, m - noun 3", chapter: 6},
    {latin: "senex", english: "old man", info: "senis, m - noun 3", chapter: 4},
    {latin: "sentio", english: "feel, notice", info: "sentire, sensi, sensus - verb 4", chapter: 9},
    {latin: "sequor", english: "follow", info: "sequi, secutus sum - verb 3 deponent", chapter: 9},
    {latin: "servo", english: "save, protect, keep", info: "servare, servavi, servatus - verb 1", chapter: 6},
    {latin: "servus", english: "slave", info: "servi, m - noun 2", chapter: 1},
    {latin: "si", english: "if", info: "indeclinable - conjunction", chapter: 8},
    {latin: "sic", english: "thus, in this way", info: "indeclinable - adverb", chapter: 7},
    {latin: "silva", english: "wood", info: "silvae, f - noun 1", chapter: 5},
    {latin: "simul", english: "at the same time", info: "indeclinable - adverb", chapter: 10},
    {latin: "simulac, simulatque", english: "as soon as", info: "indeclinable - conjunction", chapter: 10},
    {latin: "sine", english: "without", info: "+ ablative - preposition", chapter: 7},
    {latin: "soleo", english: "be accustomed", info: "solere, solitus sum - verb 2", chapter: 9},
    {latin: "solus", english: "alone, lonely, only, on one's own", info: "sola, solum - adjective", chapter: 7},
    {latin: "specto", english: "look at, watch", info: "spectare, spectavi, spectatus - verb 1", chapter: 4},
    {latin: "spero", english: "hope, expect", info: "sperare, speravi, speratus - verb 1", chapter: 9},
    {latin: "spes", english: "hope", info: "spei, f - noun 5", chapter: 10},
    {latin: "statim", english: "at once, immediately", info: "indeclinable - adverb", chapter: 3},
    {latin: "sto", english: "stand", info: "stare, steti - verb 1", chapter: 7},
    {latin: "stultus", english: "stupid, foolish", info: "stulta, stultum - adjective", chapter: 3},
    {latin: "sub", english: "under, beneath", info: "+ accusative/ablative - preposition", chapter: 8},
    {latin: "subito", english: "suddenly", info: "indeclinable - adverb", chapter: 3},
    {latin: "sum", english: "be", info: "esse, fui - verb irregular", chapter: 1},
    {latin: "summus", english: "highest, greatest, top (of)", info: "summa, summum - adjective", chapter: 8},
    {latin: "supero", english: "overcome, overpower", info: "superare, superavi, superatus - verb 1", chapter: 5},
    {latin: "surgo", english: "get up, stand up, rise", info: "surgere, surrexi - verb 3", chapter: 8},
    {latin: "suus", english: "his, her, its, their (own)", info: "sua, suum - pronoun", chapter: 5},
    {latin: "taberna", english: "shop, inn", info: "tabernae, f - noun 1", chapter: 2},
    {latin: "taceo", english: "be silent, be quiet", info: "tacere, tacui, tacitus - verb 2", chapter: 5},
    {latin: "talis", english: "such, of such a kind", info: "tale - adjective", chapter: 10},
    {latin: "tam", english: "so", info: "indeclinable - adverb", chapter: 10},
    {latin: "tamen", english: "however", info: "indeclinable - adverb", chapter: 5},
    {latin: "tandem", english: "at last, finally", info: "indeclinable - adverb", chapter: 3},
    {latin: "tantus", english: "so great, such a great", info: "tanta, tantum - adjective", chapter: 10},
    {latin: "tempestas", english: "storm", info: "tempestatis, f - noun 3", chapter: 9},
    {latin: "templum", english: "temple", info: "templi, n - noun 2", chapter: 2},
    {latin: "tempus", english: "time", info: "temporis, n - noun 3", chapter: 10},
    {latin: "teneo", english: "hold", info: "tenere, tenui, tentus - verb 2", chapter: 5},
    {latin: "terra", english: "ground, land, country", info: "terrae, f - noun 1", chapter: 3},
    {latin: "terreo", english: "frighten", info: "terrere, terrui, territus - verb 2", chapter: 2},
    {latin: "timeo", english: "fear, be afraid", info: "timere, timui - verb 2", chapter: 2},
    {latin: "tollo", english: "raise, lift up, hold up", info: "tollere, sustuli, sublatus - verb 3", chapter: 8},
    {latin: "tot", english: "so many", info: "indeclinable - adjective", chapter: 10},
    {latin: "totus", english: "whole", info: "tota, totum - adjective", chapter: 8},
    {latin: "trado", english: "hand over, hand down", info: "tradere, tradidi, traditus - verb 3", chapter: 5},
    {latin: "traho", english: "drag", info: "trahere, traxi, tractus - verb 3", chapter: 2},
    {latin: "trans", english: "across", info: "+ accusative (also used as prefix with verbs) - preposition", chapter: 6},
    {latin: "tristis", english: "sad", info: "triste - adjective", chapter: 5},
    {latin: "tu", english: "you (singular)", info: "tui - pronoun", chapter: 4},
    {latin: "tum", english: "then", info: "indeclinable - adverb", chapter: 5},
    {latin: "turba", english: "crowd", info: "turbae, f - noun 1", chapter: 4},
    {latin: "tuus", english: "your (singular), yours", info: "tua, tuum - pronoun", chapter: 4},
    {latin: "ubi", english: "where? when, where", info: "indeclinable - adverb", chapter: 4},
    {latin: "ubi", english: "where, when", info: "indeclinable - adverb", chapter: 6},
    {latin: "umquam", english: "ever", info: "indeclinable - adverb", chapter: 10},
    {latin: "unde?", english: "from where?", info: "indeclinable - adverb", chapter: 4},
    {latin: "urbs", english: "city", info: "urbis, f - noun 3", chapter: 4},
    {latin: "ut", english: "that, so that, in order that", info: "indeclinable + subjunctive - conjunction", chapter: 10},
    {latin: "ut", english: "as, when", info: "indeclinable + indicative - conjunction", chapter: 10},
    {latin: "uxor", english: "wife", info: "uxoris, f - noun 3", chapter: 6},
    {latin: "validus", english: "strong", info: "valida, validum - adjective", chapter: 10},
    {latin: "vehementer", english: "violently, loudly", info: "indeclinable - adverb", chapter: 10},
    {latin: "vendo", english: "sell", info: "vendere, vendidi, venditus - verb 3", chapter: 6},
    {latin: "venio", english: "come", info: "venire, veni - verb 4", chapter: 2},
    {latin: "verbum", english: "word", info: "verbi, n - noun 2", chapter: 2},
    {latin: "verto", english: "turn", info: "vertere, verti, versus - verb 3", chapter: 0},
    {latin: "vester", english: "your (plural), yours", info: "vestra, vestrum - pronoun", chapter: 5},
    {latin: "via", english: "street, road, way", info: "viae, f - noun 1", chapter: 3},
    {latin: "victoria", english: "victory", info: "victoriae, f - noun 1", chapter: 9},
    {latin: "video", english: "see", info: "videre, vidi, visus - verb 2", chapter: 2},
    {latin: "videor", english: "seem, appear", info: "videri, visus sum - verb 2 deponent", chapter: 8},
    {latin: "villa", english: "house, country villa", info: "villae, f - noun 1", chapter: 1},
    {latin: "vinco", english: "conquer, win, be victorious", info: "vincere, vici, victus - verb 3", chapter: 5},
    {latin: "vinum", english: "wine", info: "vini, n - noun 2", chapter: 2},
    {latin: "vir", english: "man", info: "viri, m - noun 2", chapter: 2},
    {latin: "virtus", english: "courage, virtue", info: "virtutis, f - noun 3", chapter: 7},
    {latin: "vita", english: "life", info: "vitae, f - noun 1", chapter: 9},
    {latin: "vivo", english: "live, be alive", info: "vivere, vixi - verb 3", chapter: 9},
    {latin: "voco", english: "call", info: "vocare, vocavi, vocatus - verb 1", chapter: 1},
    {latin: "volo", english: "want, wish, be willing", info: "velle, volui - verb irregular", chapter: 8},
    {latin: "vos", english: "you (plural)", info: "vestrum - pronoun", chapter: 5},
    {latin: "vox", english: "voice, shout", info: "vocis, f - noun 3", chapter: 8},
    {latin: "vulnero", english: "wound, injure", info: "vulnerare, vulneravi, vulneratus - verb 1", chapter: 9},
    {latin: "vulnus", english: "wound", info: "vulneris, n - noun 3", chapter: 9}
];
